image: node:latest

stages:
  - pages

pages:
  stage: pages
  cache:
    key: 'my-storybook'
    paths:
      - public
  script:
    - echo 'Nothing to do...'
  artifacts:
    paths:
      - public
  only:
    - master