image: node:latest

stages:
  - deployment
  - pages

deploy-storybook:
  stage: deployment
  artifacts:
    expire_in: 1 weeks
    when: always
    paths:
      - public/
  script:
    - yarn
    - yarn build
  environment:
    name: storybook/$CI_COMMIT_REF_SLUG
    url: https://jameskolean.gitlab.io/test-storybook
  only:
    - branches

pages:
  stage: pages
  script:
    - echo 'Nothing to do...'
  artifacts:
    paths:
      - public
