image: node:latest

stages:
  - setup
  - deployment
  - pages

setup:
  stage: setup
  cache:
    key: 
      files:
        - package.json
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/
  script:
    - yarn

deploy-storybook:
  stage: deployment
  artifacts:
    expire_in: 1 weeks
    when: always
    paths:
      - public/
  script:
    - echo 'building storybook/$CI_COMMIT_REF_SLUG'
    - yarn build
  environment:
    name: storybook/$CI_COMMIT_REF_SLUG
    url: https://jameskolean.gitlab.io/test-storybook
  only:
    - branches

pages:
  stage: pages
  script:
    - echo 'Nothing to do...'
  artifacts:
    paths:
      - public
