image: node:14

stages:
  - setup
  - build
  - deployment
  - pages

setup:
  stage: setup
  cache:
    key: 
      files:
        - package.json
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/
  script:
    - yarn

storybook:
  stage: build
  artifacts:
    expire_in: 1 weeks
    when: always
    paths:
      - storybook/
  script:
    - yarn build-storybook --output-dir storybook

deploy-storybook:
  stage: deployment
  script:
    - echo "Deploy to. https://jameskolean.gitlab.io/test-storybook/$CI_COMMIT_REF_SLUG/storybook/"
  environment:
    name: storybook/$CI_COMMIT_REF_SLUG
    url: https://jameskolean.gitlab.io/test-storybook/$CI_COMMIT_REF_SLUG/storybook/
    on_stop: remove-storybook
  only:
    - branches

remove-storybook:
  stage: deployment
  cache:
    key: 'my-storybook'
    paths:
      - public
  script:
    - rm -rf "public/$CI_COMMIT_REF_SLUG/storybook"
  when: manual
  variables:
    GIT_STRATEGY: none # needed to prevent "Couldn't find remote ref" error
  environment:
    name: storybook/$CI_COMMIT_REF_SLUG
    action: stop

pages:
  stage: pages
  cache:
    key: 'my-storybook'
    paths:
      - public
  script:
    - rm -rf "public/$CI_COMMIT_REF_SLUG"
    - mkdir -p "public/$CI_COMMIT_REF_SLUG";
    - mv storybook "public/$CI_COMMIT_REF_SLUG"
  artifacts:
    paths:
      - public