image: node:14

stages:
  - deployment


deploy-storybook:
  stage: deployment
  artifacts:
    expire_in: 1 weeks
    when: always
    paths:
      - public/
  script:
    - echo "---------------------------------"
    - echo "---------------------------------"
    - echo "---------------------------------"
    - echo "building storybook/$CI_COMMIT_REF_SLUG"
    - echo "$CI_COMMIT_REF_SLUG"
    - echo "$CI_JOB_STAGE"
    - echo "---------------------------------"
    - echo "---------------------------------"
    - echo "---------------------------------"
  environment:
    name: storybook/$CI_COMMIT_REF_SLUG
    url: https://jameskolean.gitlab.io/test-storybook
  only:
    - branches

